export interface WorktreeContext {
  enabled: boolean;
  suggestedName?: string;
  gitRoot: string;
  currentBranch: string;
  repoName: string;
  worktreePath?: string;
  branchName?: string;
}

export interface WorkflowContext {
  workflowName: string;
  stageName: string;
  stageDescription?: string;
  stageIndex: number;
  totalStages: number;
  previousArtifact?: string;
  expectedOutput?: string;
}

export function buildWorktreeInstructions(context: WorktreeContext): string {
  if (!context.enabled || !context.worktreePath) {
    return '';
  }

  return `
# Git Worktree Context

You are working in an isolated git worktree for this task.

## Environment
- **Worktree Path:** ${context.worktreePath}
- **Branch:** ${context.branchName}
- **Main Repository:** ${context.gitRoot}
- **Target Branch (for merge):** ${context.currentBranch}

## Important Notes
- All your file operations are isolated in this worktree
- You can use relative paths normally - your working directory is the worktree
- **CRITICAL: You MUST commit your changes before signaling completion.** Uncommitted changes will NOT be merged. Use \`git add\` and \`git commit\` to save your work.
- When your work is complete and committed, the merge process will be handled automatically
- Do NOT attempt to merge yourself - simply complete your task after committing
`.trim();
}

function buildArtifactsInstructions(): string {
  return `
# Artifacts Directory

When working with this agent manager, you have access to a shared artifacts directory at:
\`~/.agent-manager/artifacts/\`

## What are Artifacts?

Artifacts are documents generated by agents containing:
- Implementation plans and design documents
- Research findings and analysis results
- Architecture decisions and technical specifications
- Investigation reports and debugging notes
- Code review summaries
- Any other persistent documentation from agent work

## When to Use Artifacts

**Save artifacts when:**
- You create an implementation plan for a complex task
- You perform research or analysis that should be referenced later
- You document findings from an investigation or debugging session
- You create specifications or design documents
- You generate any documentation that might be useful to other agents or future work

**Read artifacts when:**
- Another agent has documented findings relevant to your task
- You need to reference a previous implementation plan
- You're working on a related task and need context
- You're investigating an issue that may have been documented before

## Artifact Templates

Artifacts support YAML frontmatter for structured metadata. When creating artifacts, include frontmatter at the top of the file to specify the template type and metadata.

### Available Templates

**plan** - Implementation Plan
- Required fields: title, phases
- Optional fields: agent, notes
- Use for: Phased implementation plans with status tracking

**research** - Research Report
- Required fields: title
- Optional fields: agent, summary, findings
- Use for: Research findings and analysis results

**investigation** - Investigation Report
- Required fields: title
- Optional fields: agent, issue, root_cause, solution
- Use for: Debugging sessions and investigation results

### Example with Frontmatter

\`\`\`markdown
---
template: plan
version: 1
title: Authentication Implementation
created: 2024-03-15
agent: auth-agent-001
phases:
  - name: Research
    status: completed
  - name: Design
    status: in_progress
  - name: Implementation
    status: pending
---

# Authentication Implementation

## Phase 1: Research
Findings from OAuth provider investigation...

## Phase 2: Design
Architecture decisions...
\`\`\`

## Usage Guidelines

- Use descriptive filenames with dates: \`2024-03-15-auth-implementation-plan.md\`
- Prefer markdown format with YAML frontmatter
- Include timestamps and author information in the frontmatter
- Reference related artifacts by filename when applicable
- Keep artifacts focused and well-organized
- Remove or archive obsolete artifacts when appropriate

## Example

\`\`\`bash
# Save an implementation plan with frontmatter
cat > ~/.agent-manager/artifacts/2024-03-15-user-auth-plan.md << 'EOF'
---
template: plan
version: 1
title: User Authentication Implementation
created: 2024-03-15
agent: auth-agent
phases:
  - name: Research
    status: completed
  - name: Implementation
    status: pending
---

# User Authentication Implementation

## Overview
...implementation details...
EOF

# Read an existing artifact
cat ~/.agent-manager/artifacts/2024-03-15-user-auth-plan.md
\`\`\`

This shared directory helps maintain continuity across different agent sessions and enables collaboration between agents working on related tasks.
`.trim();
}

function buildWorkflowInstructions(context: WorkflowContext): string {
  const parts: string[] = [];

  parts.push(`# Workflow Context`);
  parts.push('');
  parts.push(`You are executing stage ${context.stageIndex + 1} of ${context.totalStages} in the **${context.workflowName}** workflow.`);
  parts.push('');
  parts.push(`## Current Stage: ${context.stageName}`);

  if (context.stageDescription) {
    parts.push(context.stageDescription);
  }

  if (context.previousArtifact) {
    parts.push('');
    parts.push(`## CRITICAL: Previous Stage Artifact`);
    parts.push('');
    parts.push(`**IMPORTANT: The previous stage has already completed work that you MUST build upon.**`);
    parts.push('');
    parts.push(`Before doing ANY exploration or research, you MUST first read the artifact from the previous stage:`);
    parts.push('');
    parts.push(`\`\`\`bash`);
    parts.push(`cat "${context.previousArtifact}"`);
    parts.push(`\`\`\``);
    parts.push('');
    parts.push(`This artifact contains findings, analysis, or plans from the previous stage that are ESSENTIAL context for your work.`);
    parts.push(`Do NOT start from scratch. Do NOT re-explore what has already been researched.`);
    parts.push(`Read the artifact FIRST, then continue from where the previous stage left off.`);
  }

  if (context.expectedOutput) {
    parts.push('');
    parts.push(`## Expected Output`);
    parts.push(`This stage should produce a **${context.expectedOutput}** artifact.`);
    parts.push(`Save your output to \`~/.agent-manager/artifacts/\` using the appropriate template.`);
  }

  parts.push('');
  parts.push(`## Workflow Guidelines`);
  if (context.previousArtifact) {
    parts.push(`- **READ THE PREVIOUS ARTIFACT FIRST** - this is mandatory`);
  }
  parts.push(`- Build upon work from previous stages - do not duplicate effort`);
  parts.push(`- Focus on the specific objectives of this stage`);
  parts.push(`- Produce clear, well-documented output for the next stage`);

  return parts.join('\n');
}

export function buildSystemPrompt(worktreeContext?: WorktreeContext, workflowContext?: WorkflowContext): string {
  const parts: string[] = [];

  parts.push(buildArtifactsInstructions());

  if (worktreeContext?.enabled && worktreeContext.worktreePath) {
    parts.push(buildWorktreeInstructions(worktreeContext));
  }

  if (workflowContext) {
    parts.push(buildWorkflowInstructions(workflowContext));
  }

  return parts.join('\n\n');
}
